#!/bin/sh
export HOSTNAME=imx
export root=root
export PS1="\[\e[36;1m$root@$HOSTNAME\e[0m: \e[34;1m\w\e[0m\]\$ "
PATH=/bin:/sbin:/usr/bin:/usr/sbin
LD_LIBRARY_PATH=/lib:/usr/lib:$LD_LIBRARY_PATH
export PATH LD_LIBRARY_PATH
